name: update_mindmap_image
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
    - name: Setup Action
      uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '14'     
    - name: Update image
      run: chmod +x ./generate_mindmap_image.sh; bash ./generate_mindmap_image.sh

